<?php
/**
 * Plugin Name: CLASSS Core
 * Description: Project CMS, enquiry pipeline, WooCommerce customer requests and staged demo setup for CLASSS.
 * Version: 0.1.0
 * Author: Projiverse
 * Requires PHP: 8.1
 * License: GPL-2.0-or-later
 */
if (!defined('ABSPATH')) exit;
function classs_register_content() {
 register_post_type('classs_project',['labels'=>['name'=>'Projects','singular_name'=>'Project'],'public'=>true,'has_archive'=>'projects','rewrite'=>['slug'=>'project'],'show_in_rest'=>true,'menu_icon'=>'dashicons-hammer','supports'=>['title','editor','excerpt','thumbnail','custom-fields']]);
 register_taxonomy('classs_category','classs_project',['label'=>'Project categories','public'=>true,'hierarchical'=>true,'show_in_rest'=>true]);
 register_post_type('classs_enquiry',['labels'=>['name'=>'CLASSS Enquiries','singular_name'=>'Enquiry'],'public'=>false,'show_ui'=>true,'show_in_rest'=>false,'menu_icon'=>'dashicons-email-alt','supports'=>['title'],'capabilities'=>['edit_post'=>'manage_options','read_post'=>'manage_options','delete_post'=>'manage_options','edit_posts'=>'manage_options','edit_others_posts'=>'manage_options','publish_posts'=>'manage_options','read_private_posts'=>'manage_options','delete_posts'=>'manage_options','delete_private_posts'=>'manage_options','delete_published_posts'=>'manage_options','delete_others_posts'=>'manage_options','edit_private_posts'=>'manage_options','edit_published_posts'=>'manage_options','create_posts'=>'manage_options'],'map_meta_cap'=>false]);
 foreach(['branch','technology','difficulty','budget','image_url','how','applications','components','video','document','seo_title','seo_description','image_alt','featured'] as $key) register_post_meta('classs_project','classs_'.$key,['single'=>true,'type'=>'string','show_in_rest'=>true,'sanitize_callback'=>in_array($key,['image_url','video','document'],true)?'esc_url_raw':'sanitize_text_field','auth_callback'=>function($allowed,$meta_key,$post_id){return current_user_can('edit_post',$post_id);}]);
 add_rewrite_endpoint('classs-requests',EP_ROOT|EP_PAGES);
}
add_action('init','classs_register_content');
register_activation_hook(__FILE__,function(){classs_register_content();flush_rewrite_rules();});
register_deactivation_hook(__FILE__,function(){flush_rewrite_rules();});
add_action('pre_get_posts',function($q){if(is_admin()||!$q->is_main_query())return;if($q->is_post_type_archive('classs_project')||$q->get('post_type')==='classs_project'){ $m=[];foreach(['branch','difficulty','technology'] as $key) if(!empty($_GET[$key])) $m[]=['key'=>'classs_'.$key,'value'=>sanitize_text_field(wp_unslash($_GET[$key]))];if($m)$q->set('meta_query',$m);$q->set('posts_per_page',12);}});
add_action('add_meta_boxes',function(){add_meta_box('classs-project-data','Project specifications & presentation','classs_project_fields','classs_project','normal','high');add_meta_box('classs-enquiry-data','Requirement & quotation','classs_enquiry_fields','classs_enquiry','normal','high');});
function classs_project_fields($post){wp_nonce_field('classs_save_fields','classs_fields_nonce');foreach(['branch'=>'Branch','technology'=>'Technology','difficulty'=>'Difficulty','budget'=>'Indicative budget (₹)','image_url'=>'Illustrative image URL (prefer own media)','image_alt'=>'Image alt text','how'=>'How it works','applications'=>'Applications','components'=>'Related WooCommerce product IDs (comma separated)','video'=>'Video URL','document'=>'Approved public document URL','seo_title'=>'SEO title','seo_description'=>'SEO description','featured'=>'Featured on homepage (1 or 0)'] as $k=>$label){echo '<p><label><strong>'.esc_html($label).'</strong><br><input style="width:100%" name="classs_'.$k.'" value="'.esc_attr(get_post_meta($post->ID,'classs_'.$k,true)).'"></label></p>';}}
function classs_enquiry_fields($post){wp_nonce_field('classs_save_fields','classs_fields_nonce');foreach(['kind','name','email','mobile','org','requirement','deadline','material','colour','quantity'] as $k)echo '<p><b>'.esc_html(ucfirst($k)).':</b> '.esc_html(get_post_meta($post->ID,'classs_'.$k,true)).'</p>'; $status=get_post_meta($post->ID,'classs_status',true);echo '<p><label>Status <select name="classs_status">';foreach(['New','Contacted','Quote sent','Confirmed','Completed'] as $s)echo '<option '.selected($status,$s,false).'>'.esc_html($s).'</option>';echo '</select></label></p><p><label>Quoted amount (₹)<br><input name="classs_quote" type="number" min="0" value="'.esc_attr(get_post_meta($post->ID,'classs_quote',true)).'"></label></p><p><label>Team notes<br><textarea name="classs_notes" style="width:100%">'.esc_textarea(get_post_meta($post->ID,'classs_notes',true)).'</textarea></label></p>';}
add_action('save_post',function($id){if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(!isset($_POST['classs_fields_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['classs_fields_nonce'])),'classs_save_fields'))return;if(!current_user_can('edit_post',$id))return;$type=get_post_type($id);$keys=$type==='classs_project'?['branch','technology','difficulty','budget','image_url','image_alt','how','applications','components','video','document','seo_title','seo_description','featured']:($type==='classs_enquiry'?['status','quote','notes']:[]);foreach($keys as $k)if(isset($_POST['classs_'.$k]))update_post_meta($id,'classs_'.$k,in_array($k,['image_url','video','document'],true)?esc_url_raw(wp_unslash($_POST['classs_'.$k])):sanitize_textarea_field(wp_unslash($_POST['classs_'.$k])));});
add_shortcode('classs_request_form',function($atts){$a=shortcode_atts(['kind'=>'Service'],$atts);$kind=in_array($a['kind'],['Project','Service','3D Printing','Bulk','Future Tech'],true)?$a['kind']:'Service';ob_start();if(isset($_GET['request_saved']))echo '<div class="notice">Your requirement has been recorded. Contact the team for follow-up.</div>'; ?>
<form class="classs-form panel" method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="classs_request"><input type="hidden" name="kind" value="<?php echo esc_attr($kind); ?>"><?php wp_nonce_field('classs_submit_request','classs_request_nonce'); ?><div class="honeypot" aria-hidden="true"><label>Leave this field blank<input name="website_url" tabindex="-1" autocomplete="off"></label></div><div class="form-grid"><label>Name<input name="name" required maxlength="120"></label><label>Email<input name="email" type="email" required maxlength="180" value="<?php echo esc_attr(is_user_logged_in()?wp_get_current_user()->user_email:''); ?>"></label><label>Mobile<input name="mobile" required pattern="[0-9+ ()-]{8,20}" maxlength="20"></label><label>School / college / company<input name="org" maxlength="200"></label><label class="full">Requirement<textarea name="requirement" required maxlength="5000"><?php echo is_singular('classs_project')?esc_textarea(get_the_title()):''; ?></textarea></label><label>Deadline<input name="deadline" type="date"></label><?php if($kind==='3D Printing'): ?><label>Material<select name="material"><option>PLA</option><option>PETG</option><option>ABS</option><option>Resin</option></select></label><label>Colour<input name="colour" maxlength="50"></label><label>Quantity<input name="quantity" type="number" min="1" max="1000" value="1"></label><?php endif; ?></div><p class="notice">File upload is not enabled in this foundation. Private storage must be configured before collecting models or institutional documents.</p><label><input type="checkbox" name="consent" value="1" required> I agree to be contacted about this requirement.</label><button class="btn blue" type="submit">Request quotation</button></form>
<?php return ob_get_clean();});
function classs_submit_request(){if(!isset($_POST['classs_request_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['classs_request_nonce'])),'classs_submit_request'))wp_die('Please reload the form and try again.',403);if(!empty($_POST['website_url']))wp_die('Submission rejected.',400);$ip=isset($_SERVER['REMOTE_ADDR'])?sanitize_text_field(wp_unslash($_SERVER['REMOTE_ADDR'])):'';$rate='classs_req_'.substr(hash_hmac('sha256',$ip,wp_salt()),0,28);$count=(int)get_transient($rate);if($count>=5)wp_die('Please wait before sending another request.',429);$email=isset($_POST['email'])?sanitize_email(wp_unslash($_POST['email'])):'';$name=isset($_POST['name'])?sanitize_text_field(wp_unslash($_POST['name'])):'';$req=isset($_POST['requirement'])?sanitize_textarea_field(wp_unslash($_POST['requirement'])):'';$mobile=isset($_POST['mobile'])?sanitize_text_field(wp_unslash($_POST['mobile'])):'';if(!$name||!is_email($email)||!$req||strlen($req)>5000||!preg_match('/^[0-9+ ()-]{8,20}$/',$mobile)||empty($_POST['consent']))wp_die('Check the required fields.',400);$kind=isset($_POST['kind'])?sanitize_text_field(wp_unslash($_POST['kind'])):'Service';if(!in_array($kind,['Project','Service','3D Printing','Bulk','Future Tech'],true))$kind='Service';$id=wp_insert_post(['post_type'=>'classs_enquiry','post_status'=>'private','post_author'=>get_current_user_id(),'post_title'=>$kind.' — '.$name],true);if(is_wp_error($id))wp_die('Could not save the request. Please try again.',500);foreach(['name','email','mobile','org','requirement','deadline','material','colour','quantity'] as $k)if(isset($_POST[$k]))update_post_meta($id,'classs_'.$k,$k==='email'?$email:sanitize_textarea_field(wp_unslash($_POST[$k])));update_post_meta($id,'classs_kind',$kind);update_post_meta($id,'classs_status','New');set_transient($rate,$count+1,HOUR_IN_SECONDS);$back=wp_get_referer();wp_safe_redirect(add_query_arg('request_saved','1',$back?:home_url('/')));exit;}
add_action('admin_post_classs_request','classs_submit_request');add_action('admin_post_nopriv_classs_request','classs_submit_request');
add_filter('woocommerce_account_menu_items',function($items){$items['classs-requests']='Project requests';return $items;});
add_action('woocommerce_account_classs-requests_endpoint',function(){if(!is_user_logged_in())return;$q=new WP_Query(['post_type'=>'classs_enquiry','post_status'=>'private','author'=>get_current_user_id(),'posts_per_page'=>30]);echo '<h2>Your project requests</h2>';while($q->have_posts()){$q->the_post();$id=get_the_ID();echo '<div class="panel" style="margin:20px 0"><h3>'.esc_html(get_the_title()).'</h3><p>'.esc_html(get_post_meta($id,'classs_requirement',true)).'</p><p>Status: '.esc_html(get_post_meta($id,'classs_status',true)).'</p><p>Quote: ₹'.esc_html(get_post_meta($id,'classs_quote',true)).'</p></div>';}wp_reset_postdata();});
add_action('customize_register',function($c){$c->add_section('classs_brand',['title'=>'CLASSS homepage']);foreach(['hero_heading'=>'Have an idea?','hero_accent'=>'We build it.','hero_description'=>'Discover your next project, find the right components, and turn a great idea into something real.','hero_image'=>'https://upload.wikimedia.org/wikipedia/commons/9/9b/Robot_arm_works_on_a_small_component_in_a_lab_setting.jpg'] as $key=>$default){$c->add_setting('classs_'.$key,['default'=>$default,'sanitize_callback'=>$key==='hero_image'?'esc_url_raw':'sanitize_text_field']);$c->add_control('classs_'.$key,['section'=>'classs_brand','label'=>ucwords(str_replace('_',' ',$key)),'type'=>$key==='hero_image'?'url':'text']);}});
add_action('admin_menu',function(){add_options_page('CLASSS Setup','CLASSS Setup','manage_options','classs-setup','classs_setup_page');});
function classs_setup_page(){if(!current_user_can('manage_options'))return;echo '<div class="wrap"><h1>CLASSS staging setup</h1><p>Install WooCommerce, activate the CLASSS Engineering theme, then import illustrative content on a staging site. Repeated imports skip existing sample items.</p>';if(isset($_POST['classs_seed'])){check_admin_referer('classs_seed');classs_seed_data();echo '<div class="notice notice-success"><p>Sample content imported. Configure WooCommerce settings and permalinks next.</p></div>';}if(isset($_POST['classs_settings'])){check_admin_referer('classs_settings');update_option('classs_whatsapp',preg_replace('/\D/','',wp_unslash($_POST['whatsapp']??'')));echo '<p>Contact setting saved.</p>';}echo '<form method="post">';wp_nonce_field('classs_seed');echo '<input type="hidden" name="classs_seed" value="1"><button class="button button-primary">Import staging sample content</button></form><hr><form method="post">';wp_nonce_field('classs_settings');echo '<input type="hidden" name="classs_settings" value="1"><label>WhatsApp number with country code <input name="whatsapp" value="'.esc_attr(get_option('classs_whatsapp','')).'"></label><button class="button">Save</button></form><p>No payment, shipping, private file storage or email provider is automatically connected.</p></div>';}
function classs_seed_data(){ $seed=json_decode(file_get_contents(__DIR__.'/sample-data.json'),true);if(!$seed)return;$map=[];if(class_exists('WC_Product_Simple'))foreach($seed['products'] as $p){$existing=wc_get_product_id_by_sku($p['sku']);if($existing){$map[$p['id']]=$existing;continue;}$product=new WC_Product_Simple();$product->set_name($p['title']);$product->set_status('publish');$product->set_description($p['description'].'<p>Illustrative sample item. Confirm final specifications and images before accepting orders.</p>');$product->set_regular_price((string)$p['price']);$product->set_sku($p['sku']);$product->set_manage_stock(true);$product->set_stock_quantity($p['stock']);$id=$product->save();$map[$p['id']]=$id;update_post_meta($id,'classs_image_url',$p['image']);$term=term_exists($p['category'],'product_cat');if(!$term)$term=wp_insert_term($p['category'],'product_cat');if(!is_wp_error($term))wp_set_object_terms($id,(int)$term['term_id'],'product_cat');}
 foreach($seed['projects'] as $p){$exists=get_posts(['post_type'=>'classs_project','post_status'=>'any','meta_key'=>'classs_seed_id','meta_value'=>$p['id'],'numberposts'=>1]);if($exists)continue;$id=wp_insert_post(['post_type'=>'classs_project','post_status'=>'publish','post_title'=>$p['title'],'post_name'=>$p['id'],'post_content'=>$p['description']]);foreach(['branch','technology','difficulty','budget','how','applications'] as $k)update_post_meta($id,'classs_'.$k,(string)$p[$k]);update_post_meta($id,'classs_seed_id',$p['id']);update_post_meta($id,'classs_featured',$p['featured']?'1':'0');update_post_meta($id,'classs_image_url',$p['image']);update_post_meta($id,'classs_components',implode(',',array_filter(array_map(function($key)use($map){return $map[$key]??0;},$p['components']))));wp_set_object_terms($id,$p['category'],'classs_category');}
 $pages=['home'=>['Home',''],'services'=>['Services','<h2>Engineering, end to end.</h2><p>Project development, PCB design, automation, lab setup, website development, app development and IoT solutions.</p>[classs_request_form kind="Service"]'],'3d-printing'=>['3D Printing','<h2>Your design. Made physical.</h2><p>Request materials, colours, quantity and deadline. Private model upload will be connected before launch.</p>[classs_request_form kind="3D Printing"]'],'bulk-orders'=>['Bulk Orders','<h2>One requirement. A complete solution.</h2><p>For schools, colleges, labs, companies and dealers.</p>[classs_request_form kind="Bulk"]'],'future-tech'=>['Future Tech','<h2>Explore what is possible next.</h2><p>Robotics, drones, edge AI, wearables, VR and AR-MR solutions.</p>[classs_request_form kind="Future Tech"]']];
 $credits=json_decode(file_get_contents(__DIR__.'/image-credits.json'),true);$credit_html='<p>Illustrative photographs; not confirmed CLASSS stock. Images cropped for display.</p>';foreach($credits as $c)$credit_html.='<p><a href="'.esc_url($c['source']).'">'.esc_html($c['name']).'</a> — '.esc_html($c['credit']).' · <a href="'.esc_url($c['licenseUrl']).'">'.esc_html($c['license']).'</a></p>';$pages['image-credits']=['Image credits',$credit_html];
 foreach($pages as $slug=>$v){$page=get_page_by_path($slug);$id=$page?$page->ID:wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_name'=>$slug,'post_title'=>$v[0],'post_content'=>$v[1]]);if($slug==='home'){update_option('show_on_front','page');update_option('page_on_front',$id);}}
 flush_rewrite_rules();
}
add_filter('woocommerce_product_get_image',function($html,$product){if($product->get_image_id())return $html;$url=get_post_meta($product->get_id(),'classs_image_url',true);return $url?'<img src="'.esc_url($url).'" alt="'.esc_attr($product->get_name()).'" loading="lazy">':$html;},10,2);
add_filter('pre_get_document_title',function($title){if(is_singular('classs_project')){$custom=get_post_meta(get_queried_object_id(),'classs_seo_title',true);if($custom)return $custom.' | CLASSS Projects';}return $title;});
add_action('wp_head',function(){if(!is_singular('classs_project'))return;$id=get_queried_object_id();$desc=get_post_meta($id,'classs_seo_description',true);if(!$desc)$desc=wp_trim_words(wp_strip_all_tags(get_post_field('post_content',$id)),30);echo '<meta name="description" content="'.esc_attr($desc).'">';echo '<script type="application/ld+json">'.wp_json_encode(['@context'=>'https://schema.org','@type'=>'CreativeWork','name'=>get_the_title($id),'description'=>$desc,'url'=>get_permalink($id)],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT).'</script>';});
